# Generated by Django 5.2 on 2025-08-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GastoOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_literal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "costo_parcial",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_modificacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IdentificadorGeneral",
            fields=[
                ("id_general", models.AutoField(primary_key=True, serialize=False)),
                ("NombreProyecto", models.CharField(max_length=255, unique=True)),
                ("carga_social", models.DecimalField(decimal_places=2, max_digits=5)),
                ("impuestos_iva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("herramientas", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "gastos_generales",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("iva_efectiva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("it", models.DecimalField(decimal_places=2, max_digits=5)),
                ("iue", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ganancia", models.DecimalField(decimal_places=2, max_digits=5)),
                ("a_costo_venta", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "b_margen_utilidad",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porcentaje_global_100",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("telefono", models.CharField(max_length=20)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("ci", models.CharField(max_length=20, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("imagen_url", models.URLField(blank=True, max_length=500, null=True)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EquipoHerramienta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "id_gasto_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gastooperacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GastosGeneralesAdministrativos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "id_gasto_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gastooperacion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gastooperacion",
            name="identificador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.identificadorgeneral",
            ),
        ),
        migrations.CreateModel(
            name="ManoDeObra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "id_gasto_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gastooperacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materiales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "id_gasto_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gastooperacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolPermiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.permiso"
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.rol"
                    ),
                ),
            ],
            options={
                "unique_together": {("rol", "permiso")},
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.rol"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "rol")},
            },
        ),
    ]
