# Generated by Django 4.2.11 on 2025-12-11 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("payload", models.TextField(blank=True, null=True)),
                ("tipos", models.TextField()),
                ("descripcion", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("bloqueado", models.BooleanField(default=False)),
                ("url", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GastoOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_literal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "costo_parcial",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                ("id_proyecto", models.AutoField(primary_key=True, serialize=False)),
                ("NombreProyecto", models.CharField(max_length=255, unique=True)),
                ("carga_social", models.DecimalField(decimal_places=2, max_digits=5)),
                ("iva_efectiva", models.DecimalField(decimal_places=2, max_digits=5)),
                ("herramientas", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "gastos_generales",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "iva_tasa_nominal",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("it", models.DecimalField(decimal_places=2, max_digits=5)),
                ("iue", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ganancia", models.DecimalField(decimal_places=2, max_digits=5)),
                ("a_costo_venta", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "b_margen_utilidad",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "porcentaje_global_100",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroPendiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("datos", models.JSONField()),
                ("correo", models.EmailField(max_length=254)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("verificado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("telefono", models.CharField(max_length=20)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("ci", models.CharField(max_length=20, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("imagen_url", models.URLField(blank=True, max_length=500, null=True)),
                ("estado", models.BooleanField(default=True)),
                ("intentos_fallidos", models.IntegerField(default=0)),
                ("ultimo_intento", models.DateTimeField(blank=True, null=True)),
                ("fecha_cambio_password", models.DateTimeField(blank=True, null=True)),
                ("logins_exitosos", models.IntegerField(default=0)),
                (
                    "tipo_2fa",
                    models.CharField(
                        choices=[
                            ("correo", "Correo"),
                            ("totp", "Google Authenticator"),
                        ],
                        default="correo",
                        max_length=20,
                    ),
                ),
                ("secret_2fa", models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TempPasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("temp_password", models.CharField(max_length=128)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("usado", models.BooleanField(default=False)),
                ("expirado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos",
                        to="users.proyecto",
                    ),
                ),
            ],
            options={
                "unique_together": {("proyecto", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="Materiales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "id_gasto_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gastooperacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManoDeObra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "id_gasto_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gastooperacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GastosGenerales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "id_gasto_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gastooperacion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gastooperacion",
            name="identificador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.proyecto"
            ),
        ),
        migrations.AddField(
            model_name="gastooperacion",
            name="modulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gastos",
                to="users.modulo",
            ),
        ),
        migrations.CreateModel(
            name="EquipoHerramienta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("unidad", models.CharField(max_length=50)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "id_gasto_operacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.gastooperacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Codigo2FA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=6)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("expirado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.rol"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "rol")},
            },
        ),
        migrations.CreateModel(
            name="RolPermiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.permiso"
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.rol"
                    ),
                ),
            ],
            options={
                "unique_together": {("rol", "permiso")},
            },
        ),
    ]
