# Generated by Django 4.2.11 on 2026-06-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="secret_2fa",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_2fa",
            field=models.CharField(default="correo", max_length=20),
        ),
    ]
