# Generated by Django 4.2.11 on 2026-01-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipoherramienta",
            name="cantidad",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="manodeobra",
            name="cantidad",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="materiales",
            name="cantidad",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
