# Generated by Django 4.2.11 on 2025-10-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="atacante",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
