# Generated by Django 4.2.11 on 2026-05-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="imagen_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
