# Generated by Django 4.2.11 on 2026-04-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiene_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
