# Generated by Django 4.2.11 on 2025-10-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_codigo2fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="secret_2fa",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_2fa",
            field=models.CharField(
                choices=[("correo", "Correo"), ("totp", "Google Authenticator")],
                default="correo",
                max_length=20,
            ),
        ),
    ]
