# Generated by Django 4.2.11 on 2026-04-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_tiene_2fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tiene_2fa',
        ),
    ]
