# Generated by Django 4.2.11 on 2026-06-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usuario_secret_2fa_usuario_tipo_2fa"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastooperacion",
            name="orden",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
