# Generated by Django 4.2.11 on 2025-10-06 00:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usuario_secret_2fa_usuario_tipo_2fa"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempPasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("temp_password", models.CharField(max_length=128)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("usado", models.BooleanField(default=False)),
                ("expirado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuario"
                    ),
                ),
            ],
        ),
    ]
