--
-- PostgreSQL database dump
--

\restrict PRWiKZ3Rq1i1MioIowhOiRP4XITCn2xiPCMdDQF8rA2kfdjpldaE2j2nH183Pb9

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg12+2)
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: otp_static_staticdevice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_static_staticdevice (
    id integer NOT NULL,
    name character varying(64) NOT NULL,
    confirmed boolean NOT NULL,
    user_id integer NOT NULL,
    throttling_failure_count integer NOT NULL,
    throttling_failure_timestamp timestamp with time zone,
    created_at timestamp with time zone,
    last_used_at timestamp with time zone,
    CONSTRAINT otp_static_staticdevice_throttling_failure_count_check CHECK ((throttling_failure_count >= 0))
);


--
-- Name: otp_static_staticdevice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otp_static_staticdevice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_static_staticdevice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_static_statictoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_static_statictoken (
    id integer NOT NULL,
    token character varying(16) NOT NULL,
    device_id integer NOT NULL
);


--
-- Name: otp_static_statictoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otp_static_statictoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_static_statictoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_totp_totpdevice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_totp_totpdevice (
    id integer NOT NULL,
    name character varying(64) NOT NULL,
    confirmed boolean NOT NULL,
    key character varying(80) NOT NULL,
    step smallint NOT NULL,
    t0 bigint NOT NULL,
    digits smallint NOT NULL,
    tolerance smallint NOT NULL,
    drift smallint NOT NULL,
    last_t bigint NOT NULL,
    user_id integer NOT NULL,
    throttling_failure_count integer NOT NULL,
    throttling_failure_timestamp timestamp with time zone,
    created_at timestamp with time zone,
    last_used_at timestamp with time zone,
    CONSTRAINT otp_totp_totpdevice_digits_check CHECK ((digits >= 0)),
    CONSTRAINT otp_totp_totpdevice_step_check CHECK ((step >= 0)),
    CONSTRAINT otp_totp_totpdevice_throttling_failure_count_check CHECK ((throttling_failure_count >= 0)),
    CONSTRAINT otp_totp_totpdevice_tolerance_check CHECK ((tolerance >= 0))
);


--
-- Name: otp_totp_totpdevice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otp_totp_totpdevice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_totp_totpdevice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_atacante; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_atacante (
    id bigint NOT NULL,
    ip inet NOT NULL,
    fingerprint character varying(64) NOT NULL,
    user_agent text,
    payload text,
    tipos text NOT NULL,
    descripcion text NOT NULL,
    fecha timestamp with time zone NOT NULL,
    bloqueado boolean NOT NULL,
    url text
);


--
-- Name: users_atacante_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_atacante ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_atacante_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_codigo2fa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_codigo2fa (
    id bigint NOT NULL,
    codigo character varying(6) NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    expirado boolean NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: users_codigo2fa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_codigo2fa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_codigo2fa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_equipoherramienta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_equipoherramienta (
    id bigint NOT NULL,
    descripcion character varying(255) NOT NULL,
    unidad character varying(50) NOT NULL,
    cantidad numeric(10,5) NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    gasto_operacion_id bigint NOT NULL
);


--
-- Name: users_equipoherramienta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_equipoherramienta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_equipoherramienta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_gastooperacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_gastooperacion (
    id bigint NOT NULL,
    descripcion character varying(255) NOT NULL,
    unidad character varying(50) NOT NULL,
    cantidad numeric(10,2) NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    costo_parcial numeric(12,2) NOT NULL,
    modulo_id bigint NOT NULL
);


--
-- Name: users_gastooperacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_gastooperacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_gastooperacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_gastosgenerales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_gastosgenerales (
    id bigint NOT NULL,
    totalgastosgenerales numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    gasto_operacion_id bigint NOT NULL
);


--
-- Name: users_gastosgenerales_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_gastosgenerales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_gastosgenerales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_manodeobra; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_manodeobra (
    id bigint NOT NULL,
    descripcion character varying(255) NOT NULL,
    unidad character varying(50) NOT NULL,
    cantidad numeric(10,5) NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    gasto_operacion_id bigint NOT NULL
);


--
-- Name: users_manodeobra_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_manodeobra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_manodeobra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_materiales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_materiales (
    id bigint NOT NULL,
    descripcion character varying(255) NOT NULL,
    unidad character varying(50) NOT NULL,
    cantidad numeric(10,5) NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    gasto_operacion_id bigint NOT NULL
);


--
-- Name: users_materiales_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_materiales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_materiales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_modulo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_modulo (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    nombre character varying(255) NOT NULL,
    proyecto_id integer NOT NULL
);


--
-- Name: users_modulo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_modulo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_modulo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_permiso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_permiso (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    estado boolean NOT NULL
);


--
-- Name: users_permiso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_permiso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_permiso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_proyecto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_proyecto (
    id_proyecto integer NOT NULL,
    "NombreProyecto" character varying(255) NOT NULL,
    carga_social numeric(5,2) NOT NULL,
    iva_efectiva numeric(5,2) NOT NULL,
    herramientas numeric(5,2) NOT NULL,
    gastos_generales numeric(5,2) NOT NULL,
    iva_tasa_nominal numeric(5,2) NOT NULL,
    it numeric(5,2) NOT NULL,
    iue numeric(5,2) NOT NULL,
    ganancia numeric(5,2) NOT NULL,
    margen_utilidad numeric(5,2) NOT NULL,
    creado_por_id bigint NOT NULL
);


--
-- Name: users_proyecto_id_proyecto_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_proyecto ALTER COLUMN id_proyecto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_proyecto_id_proyecto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_registropendiente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_registropendiente (
    id bigint NOT NULL,
    token uuid NOT NULL,
    datos jsonb NOT NULL,
    correo character varying(254) NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    verificado boolean NOT NULL
);


--
-- Name: users_registropendiente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_registropendiente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_registropendiente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_rol (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    estado boolean NOT NULL
);


--
-- Name: users_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_rolpermiso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_rolpermiso (
    id bigint NOT NULL,
    permiso_id bigint NOT NULL,
    rol_id bigint NOT NULL
);


--
-- Name: users_rolpermiso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_rolpermiso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_rolpermiso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_temppasswordreset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_temppasswordreset (
    id bigint NOT NULL,
    token uuid NOT NULL,
    temp_password character varying(128) NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    usado boolean NOT NULL,
    expirado boolean NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: users_temppasswordreset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_temppasswordreset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_temppasswordreset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_usuario (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    fecha_nacimiento date NOT NULL,
    telefono character varying(20) NOT NULL,
    correo character varying(254) NOT NULL,
    password character varying(128) NOT NULL,
    ci character varying(20) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    imagen_url character varying(500),
    estado boolean NOT NULL,
    intentos_fallidos integer NOT NULL,
    ultimo_intento timestamp with time zone,
    fecha_cambio_password timestamp with time zone,
    logins_exitosos integer NOT NULL,
    tipo_2fa character varying(20) NOT NULL,
    secret_2fa character varying(32)
);


--
-- Name: users_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_usuariorol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_usuariorol (
    id bigint NOT NULL,
    rol_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: users_usuariorol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_usuariorol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_usuariorol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add static device	7	add_staticdevice
26	Can change static device	7	change_staticdevice
27	Can delete static device	7	delete_staticdevice
28	Can view static device	7	view_staticdevice
29	Can add static token	8	add_statictoken
30	Can change static token	8	change_statictoken
31	Can delete static token	8	delete_statictoken
32	Can view static token	8	view_statictoken
33	Can add TOTP device	9	add_totpdevice
34	Can change TOTP device	9	change_totpdevice
35	Can delete TOTP device	9	delete_totpdevice
36	Can view TOTP device	9	view_totpdevice
37	Can add atacante	10	add_atacante
38	Can change atacante	10	change_atacante
39	Can delete atacante	10	delete_atacante
40	Can view atacante	10	view_atacante
41	Can add gasto operacion	13	add_gastooperacion
42	Can change gasto operacion	13	change_gastooperacion
43	Can delete gasto operacion	13	delete_gastooperacion
44	Can view gasto operacion	13	view_gastooperacion
45	Can add modulo	17	add_modulo
46	Can change modulo	17	change_modulo
47	Can delete modulo	17	delete_modulo
48	Can view modulo	17	view_modulo
49	Can add permiso	18	add_permiso
50	Can change permiso	18	change_permiso
51	Can delete permiso	18	delete_permiso
52	Can view permiso	18	view_permiso
53	Can add proyecto	19	add_proyecto
54	Can change proyecto	19	change_proyecto
55	Can delete proyecto	19	delete_proyecto
56	Can view proyecto	19	view_proyecto
57	Can add registro pendiente	20	add_registropendiente
58	Can change registro pendiente	20	change_registropendiente
59	Can delete registro pendiente	20	delete_registropendiente
60	Can view registro pendiente	20	view_registropendiente
61	Can add rol	21	add_rol
62	Can change rol	21	change_rol
63	Can delete rol	21	delete_rol
64	Can view rol	21	view_rol
65	Can add usuario	24	add_usuario
66	Can change usuario	24	change_usuario
67	Can delete usuario	24	delete_usuario
68	Can view usuario	24	view_usuario
69	Can add equipo herramienta	12	add_equipoherramienta
70	Can change equipo herramienta	12	change_equipoherramienta
71	Can delete equipo herramienta	12	delete_equipoherramienta
72	Can view equipo herramienta	12	view_equipoherramienta
73	Can add gastos generales	14	add_gastosgenerales
74	Can change gastos generales	14	change_gastosgenerales
75	Can delete gastos generales	14	delete_gastosgenerales
76	Can view gastos generales	14	view_gastosgenerales
77	Can add mano de obra	15	add_manodeobra
78	Can change mano de obra	15	change_manodeobra
79	Can delete mano de obra	15	delete_manodeobra
80	Can view mano de obra	15	view_manodeobra
81	Can add materiales	16	add_materiales
82	Can change materiales	16	change_materiales
83	Can delete materiales	16	delete_materiales
84	Can view materiales	16	view_materiales
85	Can add rol permiso	22	add_rolpermiso
86	Can change rol permiso	22	change_rolpermiso
87	Can delete rol permiso	22	delete_rolpermiso
88	Can view rol permiso	22	view_rolpermiso
89	Can add temp password reset	23	add_temppasswordreset
90	Can change temp password reset	23	change_temppasswordreset
91	Can delete temp password reset	23	delete_temppasswordreset
92	Can view temp password reset	23	view_temppasswordreset
93	Can add codigo2fa	11	add_codigo2fa
94	Can change codigo2fa	11	change_codigo2fa
95	Can delete codigo2fa	11	delete_codigo2fa
96	Can view codigo2fa	11	view_codigo2fa
97	Can add usuario rol	25	add_usuariorol
98	Can change usuario rol	25	change_usuariorol
99	Can delete usuario rol	25	delete_usuariorol
100	Can view usuario rol	25	view_usuariorol
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	otp_static	staticdevice
8	otp_static	statictoken
9	otp_totp	totpdevice
10	users	atacante
11	users	codigo2fa
12	users	equipoherramienta
13	users	gastooperacion
14	users	gastosgenerales
15	users	manodeobra
16	users	materiales
17	users	modulo
18	users	permiso
19	users	proyecto
20	users	registropendiente
21	users	rol
22	users	rolpermiso
23	users	temppasswordreset
24	users	usuario
25	users	usuariorol
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-22 06:14:37.244386+00
2	auth	0001_initial	2026-02-22 06:14:44.248574+00
3	admin	0001_initial	2026-02-22 06:14:46.028108+00
4	admin	0002_logentry_remove_auto_add	2026-02-22 06:14:46.288761+00
5	admin	0003_logentry_add_action_flag_choices	2026-02-22 06:14:47.0732+00
6	contenttypes	0002_remove_content_type_name	2026-02-22 06:14:48.91775+00
7	auth	0002_alter_permission_name_max_length	2026-02-22 06:14:49.96249+00
8	auth	0003_alter_user_email_max_length	2026-02-22 06:14:50.921789+00
9	auth	0004_alter_user_username_opts	2026-02-22 06:14:51.359961+00
10	auth	0005_alter_user_last_login_null	2026-02-22 06:14:52.503713+00
11	auth	0006_require_contenttypes_0002	2026-02-22 06:14:52.981107+00
12	auth	0007_alter_validators_add_error_messages	2026-02-22 06:14:53.90529+00
13	auth	0008_alter_user_username_max_length	2026-02-22 06:14:54.990017+00
14	auth	0009_alter_user_last_name_max_length	2026-02-22 06:14:55.863919+00
15	auth	0010_alter_group_name_max_length	2026-02-22 06:14:56.740923+00
16	auth	0011_update_proxy_permissions	2026-02-22 06:14:57.189523+00
17	auth	0012_alter_user_first_name_max_length	2026-02-22 06:14:58.519792+00
18	otp_static	0001_initial	2026-02-22 06:15:01.425756+00
19	otp_static	0002_throttling	2026-02-22 06:15:02.636547+00
20	otp_static	0003_add_timestamps	2026-02-22 06:15:04.237387+00
21	otp_totp	0001_initial	2026-02-22 06:15:06.010227+00
22	otp_totp	0002_auto_20190420_0723	2026-02-22 06:15:07.226032+00
23	otp_totp	0003_add_timestamps	2026-02-22 06:15:09.019487+00
24	sessions	0001_initial	2026-02-22 06:15:10.553415+00
25	two_factor	0001_initial	2026-02-22 06:15:10.785754+00
26	two_factor	0002_auto_20150110_0810	2026-02-22 06:15:11.253476+00
27	two_factor	0003_auto_20150817_1733	2026-02-22 06:15:11.48169+00
28	two_factor	0004_auto_20160205_1827	2026-02-22 06:15:11.700825+00
29	two_factor	0005_auto_20160224_0450	2026-02-22 06:15:11.949326+00
30	two_factor	0006_phonedevice_key_default	2026-02-22 06:15:12.166197+00
31	two_factor	0007_auto_20201201_1019	2026-02-22 06:15:12.388174+00
32	two_factor	0008_delete_phonedevice	2026-02-22 06:15:12.606074+00
33	two_factor	0001_squashed_0008_delete_phonedevice	2026-02-22 06:15:12.820179+00
34	users	0001_initial	2026-02-22 06:15:25.6499+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: otp_static_staticdevice; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.otp_static_staticdevice (id, name, confirmed, user_id, throttling_failure_count, throttling_failure_timestamp, created_at, last_used_at) FROM stdin;
\.


--
-- Data for Name: otp_static_statictoken; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.otp_static_statictoken (id, token, device_id) FROM stdin;
\.


--
-- Data for Name: otp_totp_totpdevice; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.otp_totp_totpdevice (id, name, confirmed, key, step, t0, digits, tolerance, drift, last_t, user_id, throttling_failure_count, throttling_failure_timestamp, created_at, last_used_at) FROM stdin;
\.


--
-- Data for Name: users_atacante; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_atacante (id, ip, fingerprint, user_agent, payload, tipos, descripcion, fecha, bloqueado, url) FROM stdin;
\.


--
-- Data for Name: users_codigo2fa; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_codigo2fa (id, codigo, creado_en, expirado, usuario_id) FROM stdin;
1	035272	2026-02-22 11:44:02.719621+00	t	1
2	205008	2026-02-22 19:26:47.300594+00	t	1
3	668802	2026-02-23 01:25:46.839143+00	t	1
4	637154	2026-02-23 11:57:49.129937+00	t	1
5	511460	2026-02-23 14:07:44.664847+00	t	1
6	440178	2026-02-24 02:47:05.773278+00	t	1
7	021903	2026-02-24 03:02:18.305201+00	t	1
\.


--
-- Data for Name: users_equipoherramienta; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_equipoherramienta (id, descripcion, unidad, cantidad, precio_unitario, total, gasto_operacion_id) FROM stdin;
1	RETROEXCAVADORA 79 HP 0.8 M3	HR	0.20000	357.00	71.40	1
2	MOTOBOMBA DE 3"	HR	1.00000	31.50	31.50	1
4	EQUIPO PESADO RETROEXCAVADORA	HR	0.15000	250.00	37.50	5
16	SOLDADOR ELÉCTRICO	HR	2.00000	10.00	20.00	45
3	EQUIPO TOPOGRAFICO	HR	0.01000	10.00	0.10	3
8	EQUIPO TOPOGRAFICO	HR	8.00000	10.00	80.00	9
12	SOLDADOR ELÉCTRICO	HR	8.00000	10.00	80.00	32
9	SOLDADOR ELÉCTRICO	HR	3.00000	10.00	30.00	10
18	SOLDADOR ELÉCTRICO	HR	80.00000	10.00	800.00	50
13	SOLDADOR ELÉCTRICO	HR	3.00000	10.00	30.00	33
10	SOLDADOR ELÉCTRICO	HR	3.00000	10.00	30.00	13
19	SOLDADOR ELÉCTRICO	HR	12.00000	10.00	120.00	51
20	SOLDADOR ELÉCTRICO	HR	4.00000	10.00	40.00	52
5	SALTARIN	HR	0.10000	10.00	1.00	6
11	SALTARIN	HR	0.10000	10.00	1.00	15
21	SALTARIN	HR	0.10000	10.00	1.00	57
6	MEZCLADORA DE HORMIGÓN	HR	1.00000	10.00	10.00	7
14	MEZCLADORA DE HORMIGÓN	HR	1.00000	10.00	10.00	44
7	VIBRADOR DE HORMIGÓN	HR	0.80000	10.00	8.00	7
15	VIBRADOR DE HORMIGÓN	HR	0.80000	10.00	8.00	44
17	CAMIÓN GRUA	HR	80.00000	240.00	19200.00	50
\.


--
-- Data for Name: users_gastooperacion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_gastooperacion (id, descripcion, unidad, cantidad, precio_unitario, costo_parcial, modulo_id) FROM stdin;
25	CAMARA DE INSPECCION DE HºCº 80X80CM	PZA	4.00	5792.28	23169.12	4
1	EXCAVACIÓN COMÚN CON AGOTAMIENTO Y ENTIBADO	M3	1.00	473.54	473.54	1
41	LETREROS DE SEÑALIZACION AMBIENTAL	PZA	1.00	1041.65	1041.65	8
17	CAMA DE TIERRA CERNIDA	M3	1333.56	91.81	122434.14	4
15	RELLENO Y COMPACTADO MANUAL Y NIVELADO	M3	3981.40	64.92	258472.49	4
8	CONTRAPISO DE CASCOTE DE LADRILLO H=7 CM	M2	84.64	227.48	19253.91	3
18	PROV. Y TENDIDO TUBERIA PVC E-40 (E-C) D=6 PULG	M	241.00	135.14	32568.74	4
3	REPLANTEO Y CONTROL DE TUBERIAS	M	28690.00	1.28	36723.20	2
48	PROVISION Y COLOCACION PLACA ENTREGA DE OBRAS	PZA	1.00	3599.38	3599.38	9
53	PROVISION Y MONTAJE DE TABLERO DE DISTRIBUCION	PZA	1.00	7376.17	7376.17	9
31	MURO DE LADRILLO 6 HUECOS E=12 CM	M2	20.85	200.72	4185.01	7
2	PROVISION Y COLOCACION LETRERO DE OBRA FPS	PZA	1.00	15252.81	15252.81	2
14	LIMPIEZA Y DESBROCE	M2	104.04	5.32	553.49	3
4	INSTALACION DE FAENAS GENERAL	GLB	1.00	19052.62	19052.62	2
32	PROVISION Y COLOCACION PUERTA METALICA	M2	2.40	4654.05	11169.72	7
42	ANALISIS FISICO, QUIMICO Y MICROBIOLOGICO DE AGUAS	MTR	1.00	2152.08	2152.08	9
22	PRUEBA HIDRAULICA TUBERIA HASTA D=6"	M	21311.00	0.69	14704.59	4
49	PROV. Y TENDIDO TUBERIA PVC E-40 (E-C) D=6 PULG	M	270.00	135.14	36487.80	9
30	PROV. E INST. BOMBA ELECTRICA CENTRIFUGA 15 HP	PZA	2.00	51351.86	102703.72	6
39	CONTENEDOR DE RESIDUOS SOLIDOS	PZA	3.00	993.82	2981.46	8
55	EXCAVACION DE 0-2 M SUELO SEMIDURO	M3	86.40	67.99	5874.34	9
20	PROV. Y TENDIDO TUBERIA PVC E-40 (E-C) D=3 PULG	M	6486.00	57.56	373334.16	4
40	EVITAR CONTAMINAR SUELOS POR GRASAS Y ACEITES	GLB	1.00	3486.42	3486.42	8
19	PROV. E INST. ACCESORIOS RED DE DISTRIBUCION	GLB	1.00	47298.68	47298.68	4
36	PROV. Y COLOC. MARCO DE MADERA Y REJA DE PROTECCION (ACERO LISO 3/8")	M2	1.26	1594.23	2008.73	7
13	PROV Y COLOC TAPA METALICA (PLANCHA 3/16"-ANGULAR3/4X1/8")	M2	0.64	3102.58	1985.65	3
56	CAMA DE TIERRA CERNIDA	M3	27.00	91.81	2478.87	9
51	PROV. Y COLOC. ESTRUCTURA METALICA P/DOSIFICADORES	GLB	1.00	13309.10	13309.10	9
27	ACOMETIDA DE AGUA POTABLE	PZA	481.00	2040.56	981509.36	5
47	ACOMETIDA DE AGUA POTABLE	PZA	1.00	2040.56	2040.56	9
23	DESINFECCION DE TUBERIA HASTA D=6"	M	21311.00	0.98	20884.78	4
38	LETRINA ECOLOGICA	PZA	1.00	9097.64	9097.64	8
44	HORMIGON ARMADO H21	M3	38.40	4410.85	169376.64	9
43	CONTRAPISO DE CASCOTE DE LADRILLO H=7 CM	M2	76.80	227.48	17470.46	9
57	RELLENO Y COMPACTADO MANUAL Y NIVELADO	M3	59.40	64.92	3856.25	9
58	PROV. E INST. VALVULA COMPUERTA FFD DN=150 MM ANSI 300 LB	PZA	2.00	9227.56	18455.12	9
50	PTAP COMPACTA ABIERTA METALICA 30 M3/HR	GLB	1.00	1111756.18	1111756.18	9
6	RELLENO ZANJA CON MATERIAL GRANULAR INCL.PROV. DE MATERIAL	M3	50.44	99.99	5043.50	3
21	PROV. Y TENDIDO TUBERIA PVC E-40 (E-C) D=4 PULG	M	2263.00	75.84	171625.92	4
29	PROV. Y COLOC. DE CAJA PLASTICO PARA MEDIDOR DE AGUA	PZA	481.00	428.11	205920.91	5
34	REVOQUE Y ENLUCIDO DE CEMENTO	M2	41.68	154.64	6445.40	7
28	PROV. Y COLOCACION DE MEDIDOR DE AGUA D=1/2 PULG	PZA	481.00	310.36	149283.16	5
37	PASOS PEATONALES EN ZANJAS CON PASAMANOS	PZA	1.00	563.26	563.26	8
5	EXCAVACION COMUN CON EQUIPO PESADO	M3	270.50	52.87	14301.34	3
33	CUBIERTA DE CALAMINA GALVANIZADA Nº28 INCL. ESTRUCT. METALICA	M2	9.80	519.72	5093.26	7
54	CAMARA DE INSPECCION DE HºCº 80X80CM	PZA	2.00	5792.28	11584.56	9
12	REVOQUE INTERIOR CON IMPERMEABILIZANTE E=2,5 CM	M2	164.96	167.79	27678.64	3
11	PROV. E INST. ACCESORIOS PARA TANQUE ELEVADO DE AGUA	GLB	1.00	43790.88	43790.88	3
26	PROV. E INST. ACCESORIOS CAMARA DE VALVULAS	GLB	1.00	20088.74	20088.74	4
16	PROV. Y TENDIDO TUBERIA PVC E-40 (E-C) D=2 PULG	M	12321.00	32.01	394395.21	4
7	HORMIGON ARMADO H21	M3	66.47	4410.85	293189.20	3
45	PROVISION Y TENDIDO TUBERIA FG D=6"	M	8.58	870.47	7468.63	9
46	ACOMETIDA ELECTRICA	GLB	1.00	11952.91	11952.91	9
52	PROV. Y COLOC. REJILLA METALICA DE ACERO	M	7.20	1077.26	7756.27	9
10	ESCALERA METALICA	M	2.00	1305.93	2611.86	3
24	EXCAVACION DE 0-2 M SUELO SEMIDURO	M3	5314.96	67.99	361364.13	4
9	REPLANTEO Y TRAZADO DE OBRAS	GLB	1.00	1604.82	1604.82	3
35	PINTURA LATEX HORMIGON VISTO	M2	41.68	66.42	2768.39	7
59	PINTADO ARTISTICO OBRA FPS	GLB	1.00	27426.49	27426.49	9
\.


--
-- Data for Name: users_gastosgenerales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_gastosgenerales (id, totalgastosgenerales, total, gasto_operacion_id) FROM stdin;
2	13827.46	15252.81	2
48	3263.02	3599.38	48
50	1007864.48	1111756.18	50
32	4219.14	4654.05	32
43	206.22	227.48	43
31	181.96	200.72	31
1	417.59	473.54	1
34	140.19	154.64	34
42	1950.97	2152.08	42
33	471.15	519.72	33
25	5251.00	5792.28	25
30	46553.12	51351.86	30
41	944.31	1041.65	41
47	1849.87	2040.56	47
52	976.59	1077.26	52
40	3160.62	3486.42	40
46	10835.93	11952.91	46
9	1454.85	1604.82	9
4	17272.19	19052.62	4
51	12065.39	13309.10	51
3	1.16	1.28	3
53	6686.88	7376.17	53
11	39698.70	43790.88	11
54	5251.00	5792.28	54
5	47.93	52.87	5
10	1183.89	1305.93	10
55	61.64	67.99	55
58	8365.26	9227.56	58
56	83.23	91.81	56
57	58.85	64.92	57
13	2812.65	3102.58	13
14	4.82	5.32	14
59	24863.53	27426.49	59
6	90.65	99.99	6
16	29.02	32.01	16
18	122.51	135.14	18
27	1849.87	2040.56	27
49	122.51	135.14	49
19	42878.70	47298.68	19
15	58.85	64.92	15
21	68.75	75.84	21
17	83.23	91.81	17
28	281.36	310.36	28
22	0.63	0.69	22
39	900.95	993.82	39
37	510.62	563.26	37
35	60.21	66.42	35
36	1445.25	1594.23	36
44	3998.66	4410.85	44
7	3998.66	4410.85	7
29	388.10	428.11	29
20	52.18	57.56	20
12	152.11	167.79	12
8	206.22	227.48	8
26	18211.48	20088.74	26
38	8247.48	9097.64	38
24	61.64	67.99	24
23	0.89	0.98	23
45	789.13	870.47	45
\.


--
-- Data for Name: users_manodeobra; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_manodeobra (id, descripcion, unidad, cantidad, precio_unitario, total, gasto_operacion_id) FROM stdin;
1	CAPATAZ	HR	0.50000	23.50	11.75	1
2	OPERADOR DE EQUIPO PESADO	HR	0.25000	23.00	5.75	1
3	AYUDANTE	HR	4.00000	16.00	64.00	1
4	ALBAÑIL	HR	48.00000	15.00	720.00	2
5	AYUDANTE	HR	48.00000	10.00	480.00	2
6	PINTOR	HR	16.00000	15.00	240.00	2
7	ALARIFE	HR	0.01000	12.50	0.13	3
8	AYUDANTE	HR	0.01000	10.00	0.10	3
9	TOPOGRAFO	HR	0.01000	18.00	0.18	3
10	ALBAÑIL	HR	24.00000	15.00	360.00	4
11	AYUDANTE	HR	24.00000	10.00	240.00	4
12	ESPECIALISTA	HR	24.00000	15.00	360.00	4
13	AYUDANTE	HR	0.20000	10.00	2.00	5
14	OPERADOR DE EQUIPO PESADO	HR	0.15000	15.00	2.25	5
15	AYUDANTE	HR	3.00000	10.00	30.00	6
16	ALBAÑIL	HR	24.00000	15.00	360.00	7
17	AYUDANTE	HR	24.00000	10.00	240.00	7
18	ALBAÑIL	HR	2.20000	15.00	33.00	8
19	AYUDANTE	HR	2.20000	10.00	22.00	8
20	ALBAÑIL	HR	8.00000	15.00	120.00	9
21	AYUDANTE	HR	16.00000	10.00	160.00	9
22	TOPOGRAFO	HR	8.00000	18.00	144.00	9
23	AYUDANTE	HR	16.00000	10.00	160.00	10
24	SOLDADOR	HR	16.00000	15.00	240.00	10
25	AYUDANTE	HR	120.00000	10.00	1200.00	11
26	ESPECIALISTA	HR	120.00000	15.00	1800.00	11
27	ALBAÑIL	HR	2.20000	15.00	33.00	12
28	AYUDANTE	HR	2.20000	10.00	22.00	12
29	AYUDANTE	HR	8.00000	10.00	80.00	13
30	SOLDADOR	HR	8.00000	15.00	120.00	13
31	AYUDANTE	HR	0.25000	10.00	2.50	14
32	AYUDANTE	HR	3.00000	10.00	30.00	15
33	AYUDANTE	HR	0.15000	10.00	1.50	16
34	PLOMERO	HR	0.15000	15.00	2.25	16
35	AYUDANTE	HR	3.00000	10.00	30.00	17
36	AYUDANTE	HR	0.30000	10.00	3.00	18
37	PLOMERO	HR	0.30000	15.00	4.50	18
38	AYUDANTE	HR	120.00000	10.00	1200.00	19
39	PLOMERO	HR	120.00000	15.00	1800.00	19
40	AYUDANTE	HR	0.20000	10.00	2.00	20
41	PLOMERO	HR	0.20000	15.00	3.00	20
42	AYUDANTE	HR	0.25000	10.00	2.50	21
43	PLOMERO	HR	0.25000	15.00	3.75	21
44	AYUDANTE	HR	0.01000	10.00	0.10	22
45	PLOMERO	HR	0.01000	15.00	0.15	22
46	AYUDANTE	HR	0.01000	10.00	0.10	23
47	PLOMERO	HR	0.01000	15.00	0.15	23
48	AYUDANTE	HR	3.20000	10.00	32.00	24
49	ALBAÑIL	HR	32.00000	15.00	480.00	25
50	AYUDANTE	HR	32.00000	10.00	320.00	25
51	AYUDANTE	HR	48.00000	10.00	480.00	26
52	PLOMERO	HR	48.00000	15.00	720.00	26
53	ALBAÑIL	HR	12.00000	15.00	180.00	27
54	AYUDANTE	HR	12.00000	10.00	120.00	27
55	AYUDANTE	HR	1.00000	10.00	10.00	28
56	PLOMERO	HR	1.00000	15.00	15.00	28
57	AYUDANTE	HR	0.50000	10.00	5.00	29
58	PLOMERO	HR	0.50000	15.00	7.50	29
70	ALBAÑIL	HR	0.65800	15.00	9.87	35
60	ESPECIALISTA	HR	48.00000	15.00	720.00	30
61	INGENIERO ELÉCTRICO	HR	48.00000	35.00	1680.00	30
59	AYUDANTE	HR	48.00000	10.00	480.00	30
62	ALBAÑIL	HR	2.00000	15.00	30.00	31
63	AYUDANTE	HR	2.00000	10.00	20.00	31
64	AYUDANTE	HR	24.00000	10.00	240.00	32
65	SOLDADOR	HR	24.00000	15.00	360.00	32
66	AYUDANTE	HR	6.00000	10.00	60.00	33
67	SOLDADOR	HR	6.00000	15.00	90.00	33
68	ALBAÑIL	HR	2.20000	15.00	33.00	34
69	AYUDANTE	HR	2.20000	10.00	22.00	34
71	AYUDANTE	HR	0.65800	10.00	6.58	35
72	ALBAÑIL	HR	8.00000	15.00	120.00	36
73	AYUDANTE	HR	8.00000	10.00	80.00	36
74	ALBAÑIL	HR	4.00000	15.00	60.00	37
75	AYUDANTE	HR	4.00000	10.00	40.00	37
76	ALBAÑIL	HR	48.00000	15.00	720.00	38
77	AYUDANTE	HR	48.00000	10.00	480.00	38
78	ALBAÑIL	HR	1.00000	15.00	15.00	39
79	AYUDANTE	HR	4.00000	10.00	40.00	39
80	ALBAÑIL	HR	4.00000	15.00	60.00	40
81	AYUDANTE	HR	4.00000	10.00	40.00	40
82	AYUDANTE	HR	2.00000	10.00	20.00	41
83	ESPECIALISTA	HR	2.00000	15.00	30.00	41
84	AYUDANTE	HR	32.00000	10.00	320.00	42
85	ESPECIALISTA	HR	4.00000	15.00	60.00	42
86	ALBAÑIL	HR	2.20000	15.00	33.00	43
87	AYUDANTE	HR	2.20000	10.00	22.00	43
88	ALBAÑIL	HR	24.00000	15.00	360.00	44
89	AYUDANTE	HR	24.00000	10.00	240.00	44
90	AYUDANTE	HR	2.00000	10.00	20.00	45
91	SOLDADOR	HR	2.00000	15.00	30.00	45
92	AYUDANTE	HR	24.00000	10.00	240.00	46
93	INGENIERO ELÉCTRICO	HR	24.00000	35.00	840.00	46
94	ALBAÑIL	HR	12.00000	15.00	180.00	47
95	AYUDANTE	HR	12.00000	10.00	120.00	47
96	ALBAÑIL	HR	24.00000	15.00	360.00	48
97	AYUDANTE	HR	24.00000	10.00	240.00	48
98	AYUDANTE	HR	0.30000	10.00	3.00	49
99	PLOMERO	HR	0.30000	15.00	4.50	49
100	AYUDANTE	HR	288.00000	10.00	2880.00	50
101	ELECTRICISTA	HR	160.00000	15.00	2400.00	50
102	ESPECIALISTA	HR	80.00000	15.00	1200.00	50
103	INGENIERO ELÉCTRICO	HR	160.00000	35.00	5600.00	50
104	INGENIERO QUÍMICO	HR	80.00000	35.00	2800.00	50
105	INGENIERO MECÁNICO	HR	80.00000	35.00	2800.00	50
106	INGENIERO SANITARIO	HR	48.00000	35.00	1680.00	50
107	PLOMERO	HR	208.00000	15.00	3120.00	50
108	SOLDADOR	HR	80.00000	15.00	1200.00	50
109	AYUDANTE	HR	42.00000	10.00	420.00	51
110	SOLDADOR	HR	42.00000	15.00	630.00	51
111	AYUDANTE	HR	12.05000	10.00	120.50	52
112	SOLDADOR	HR	12.06000	15.00	180.90	52
113	AYUDANTE	HR	16.00000	10.00	160.00	53
114	INGENIERO ELÉCTRICO	HR	16.00000	35.00	560.00	53
115	ALBAÑIL	HR	32.00000	15.00	480.00	54
116	AYUDANTE	HR	32.00000	10.00	320.00	54
117	AYUDANTE	HR	3.20000	10.00	32.00	55
118	AYUDANTE	HR	3.00000	10.00	30.00	56
119	AYUDANTE	HR	3.00000	10.00	30.00	57
120	AYUDANTE	HR	24.00000	10.00	240.00	58
121	ESPECIALISTA	HR	24.00000	15.00	360.00	58
122	AYUDANTE	HR	120.00000	10.00	1200.00	59
123	ESPECIALISTA	HR	120.00000	15.00	1800.00	59
\.


--
-- Data for Name: users_materiales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_materiales (id, descripcion, unidad, cantidad, precio_unitario, total, gasto_operacion_id) FROM stdin;
1	MADERA DE CONSTRUCCIÓN	PIE2	11.00000	7.70	84.70	1
2	CLAVOS	KG	1.00000	13.75	13.75	1
38	CEMENTO	KG	20.00000	1.48	29.60	8
4	ACERO ESTRUCTURAL	KG	120.00000	8.50	1020.00	2
5	ARENA COMUN	M3	3.00000	500.00	1500.00	2
6	ARENA FINA	M3	2.00000	350.00	700.00	2
7	GRAVA	M3	4.00000	650.00	2600.00	2
8	PIEDRA MANZANA	M3	2.00000	350.00	700.00	2
42	MADERA DE ENCOFRADO	P2	60.00000	5.00	300.00	9
43	ALAMBRE DE AMARRE	KG	10.00000	16.00	160.00	9
9	LADRILLO CERAMICO DE 6 HUECOS	PZA	600.00000	1.50	900.00	2
10	MADERA DE ENCOFRADO	P2	120.00000	5.00	600.00	2
11	ALAMBRE DE AMARRE	KG	10.00000	16.00	160.00	2
12	CLAVO	KG	10.00000	16.00	160.00	2
13	LEYENDA DE LETRERO PINTADO	PZA	1.00000	1200.00	1200.00	2
14	ESTUCO	KG	0.00500	1.20	0.01	3
15	ESTACAS DE MADERA	PZA	0.08000	1.50	0.12	3
16	CLAVO	KG	0.00110	16.00	0.02	3
17	PINTURA AL OLEO	GL	0.00100	90.00	0.09	3
18	CASETA PARA EL CUIDADOR	GLB	1.00000	500.00	500.00	4
19	CERCO DE PROTECCIÓN	GLB	1.00000	1000.00	1000.00	4
20	EQUIPO DE RADIO EN OBRA	GLB	1.00000	800.00	800.00	4
21	GALPON PARA DEPOSITO	GLB	1.00000	1500.00	1500.00	4
22	INSTALACIÓN DE AGUA	GLB	1.00000	500.00	500.00	4
23	INSTALACIÓN ELÉCTRICA	GLB	1.00000	500.00	500.00	4
24	LABORATORIO EN OBRA	GLB	1.00000	1200.00	1200.00	4
25	OFICINA DE OBRA	GLB	1.00000	2000.00	2000.00	4
26	OTROS SERVICIOS	GLB	1.00000	500.00	500.00	4
27	PORTON DE INGRESO	GLB	1.00000	850.00	850.00	4
28	SANITARIOS PARA OBREROS Y PERSONAL	GLB	1.00000	1200.00	1200.00	4
29	HERRAMIENTAS	GLB	1.00000	4000.00	4000.00	4
30	MATERIAL GRANULAR PARA RELLENO	M3	1.20000	25.00	30.00	6
32	ACERO ESTRUCTURAL	KG	120.00000	8.50	1020.00	7
33	ARENA COMUN	M3	0.40000	500.00	200.00	7
34	GRAVA	M3	0.80000	650.00	520.00	7
44	CLAVO	KG	2.00000	16.00	32.00	9
36	ALAMBRE DE AMARRE	KG	2.00000	16.00	32.00	7
37	CLAVO	KG	1.50000	16.00	24.00	7
35	MADERA DE ENCOFRADO	P2	70.00000	5.00	350.00	7
39	ARENA FINA	M3	0.10000	350.00	35.00	8
40	CASCOTE DE LADRILLO	M3	0.10000	300.00	30.00	8
41	ESTUCO	KG	25.00000	1.20	30.00	9
61	TUBERÍA PVC E-40 (J.R.) D=3 PULG	ML	1.03000	38.00	39.14	20
62	LUBRICANTE PARA PVC	LT	0.04000	25.00	1.00	20
63	TUBERÍA PVC 4" ESQ 40	ML	1.05000	50.00	52.50	21
45	SOLDADURA	KG	2.00000	18.00	36.00	10
46	PINTURA ANTICORROSIVA	GL	0.20000	120.00	24.00	10
47	TUBERÍA FG SEGÚN PLANO INCLUYE ACCESORIOS	ML	10.00000	30.00	300.00	10
48	ACCESORIOS PARA TANQUE ELEVADO, SEGÚN PLANO	GLB	1.00000	32000.00	32000.00	11
50	ARENA FINA	M3	0.02500	350.00	8.75	12
51	SIKA 1 IMPERMEABILIZANTE	KG	0.50000	40.00	20.00	12
52	SOLDADURA	KG	2.00000	18.00	36.00	13
53	PINTURA ANTICORROSIVA	GL	0.20000	120.00	24.00	13
54	TAPA METÁLICA (PLANCHA 3/16" - ANGULAR 3/4 X 1/8")	M2	1.10000	2000.00	2200.00	13
55	TUBERÍA PVC E-40 (E-C) D=2 PULG	ML	1.03000	19.00	19.57	16
56	LUBRICANTE PARA PVC	LT	0.04000	25.00	1.00	16
57	TIERRA CERNIDA	M3	1.20000	20.00	24.00	17
58	TUBERÍA PVC E-40 (E-C) D=6 PULG	ML	1.03000	98.00	100.94	18
59	LUBRICANTE PARA PVC	LT	0.04000	25.00	1.00	18
60	ACCESORIOS RED DE DISTRIBUCIÓN SEGÚN PLANO	GLB	1.00000	35000.00	35000.00	19
64	LUBRICANTE PARA PVC	LT	0.04000	25.00	1.00	21
69	ACCESORIOS CÁMARA DE VÁLVULAS, SEGÚN DISEÑO	GLB	1.00000	15000.00	15000.00	26
70	MATERIAL ACOMETIDA DE AGUA POTABLE, SEGÚN DISEÑO	PZA	1.00000	1200.00	1200.00	27
67	HIPOCLORITO AL 70%	KG	0.01000	30.00	0.30	23
71	MEDIDOR DE AGUA 1/2" INCLUYE ACCESORIOS, SEGÚN DISEÑO	PZA	1.00000	220.00	220.00	28
65	AGUA POTABLE	LT	5.00000	0.03	0.13	22
66	AGUA POTABLE	LT	3.00000	0.03	0.08	23
68	CÁMARA DE INSPECCIÓN DE HºCº 80X80CM, SEGÚN DISEÑO	PZA	1.00000	3500.00	3500.00	25
73	ARENA COMUN	M3	0.02000	500.00	10.00	29
74	GRAVA	M3	0.04000	650.00	26.00	29
75	CAJA PLÁSTICA PARA MEDIDOR DE AGUA	PZA	1.00000	300.00	300.00	29
76	BOMBA ELÉCTRICA CENTRÍFUGA 15 HP INCLUYE ACCESORIOS	PZA	1.00000	38684.50	38684.50	30
78	ARENA FINA	M3	0.06000	350.00	21.00	31
79	LADRILLO CERÁMICO DE 6 HUECOS	PZA	30.00000	1.50	45.00	31
80	SOLDADURA	KG	2.00000	18.00	36.00	32
81	PINTURA ANTICORROSIVA	GL	0.20000	120.00	24.00	32
82	PUERTA METÁLICA INCLUYE BISAGRAS Y CHAPA, SEGÚN PLANO	M2	1.10000	2500.00	2750.00	32
83	PERFIL COSTANERAS	ML	2.00000	25.00	50.00	33
84	PINTURA ANTICORROSIVA	GL	0.05000	120.00	6.00	33
86	ESTRUCTURA METÁLICA INCLUYE ACCESORIOS, SEGÚN PLANO	M2	1.00000	25.00	25.00	33
85	CALAMINA PREPINTADA ONDULADA Nº 28	M2	1.20000	42.00	50.40	33
87	GANCHOS J PARA SUJECIÓN	PZA	1.50000	7.00	10.50	33
89	ARENA FINA	M3	0.05000	350.00	17.50	34
90	PINTURA LATEX	GL	0.12000	120.00	14.40	35
91	SELLADOR DE PAREDES	GL	0.10000	100.00	10.00	35
92	LIJA	HOJ	0.50000	5.00	2.50	35
93	VENTANA DE MADERA Y REJA DE PROTECCION (ACERO LISO 3/8")	M2	1.00000	1000.00	1000.00	36
94	PASO PEATONAL, SEGUN PLANO	PZA	1.00000	300.00	300.00	37
95	LETRINA ECOLOGICA, SEGUN DISEÑO	PZA	1.00000	5600.00	5600.00	38
96	CONTENEDOR DE RESIDUOS SOLIDOS	PZA	1.00000	750.00	750.00	39
97	TURRIL PARA GRASAS	PZA	1.00000	200.00	200.00	40
98	TURRIL PARA ACEITE	PZA	1.00000	200.00	200.00	40
99	GEOMEMBRANA DE POLIETILENO DE ALTA DENSIDAD (HDPE)	M2	20.00000	120.00	2400.00	40
100	SEÑALIZACION AMBIENTAL, SEGUN PLANO	PZA	1.00000	800.00	800.00	41
101	ENVASE PLÁSTICO ESTERILIZADO	PZA	4.00000	30.00	120.00	42
102	HIELERA	PZA	1.00000	200.00	200.00	42
103	HIELO	KG	4.00000	5.00	20.00	42
104	LABORATORIO ANÁLISIS DE AGUA	GLB	1.00000	810.00	810.00	42
106	ARENA FINA	M3	0.10000	350.00	35.00	43
107	CASCOTE DE LADRILLO	M3	0.10000	300.00	30.00	43
109	ACERO ESTRUCTURAL	KG	120.00000	8.50	1020.00	44
110	ARENA COMUN	M3	0.40000	500.00	200.00	44
111	GRAVA	M3	0.80000	650.00	520.00	44
112	MADERA DE ENCOFRADO	P2	70.00000	5.00	350.00	44
113	ALAMBRE DE AMARRE	KG	2.00000	16.00	32.00	44
114	CLAVO	KG	1.50000	16.00	24.00	44
115	SOLDADURA	KG	1.00000	18.00	18.00	45
116	PINTURA ANTICORROSIVA	GL	0.20000	120.00	24.00	45
117	TUBERÍA FG 6"	ML	1.02000	580.00	591.60	45
118	CABLE DE COBRE	KG	24.00000	120.00	2880.00	46
119	CABLE ELÉCTRICO ACOMETIDA	ML	60.00000	48.00	2880.00	46
120	JABALINA	PZA	5.00000	500.00	2500.00	46
121	MATERIAL ACOMETIDA DE AGUA POTABLE, SEGÚN DISEÑO	PZA	1.00000	1200.00	1200.00	47
123	ARENA COMUN	M3	0.40000	500.00	200.00	48
124	GRAVA	M3	0.60000	650.00	390.00	48
125	PLACA DE ENTREGA DE OBRA	PZA	1.00000	1250.00	1250.00	48
126	TUBERÍA PVC E-40 (E-C) D=6 PULG	ML	1.03000	98.00	100.94	49
127	LUBRICANTE PARA PVC	LT	0.04000	25.00	1.00	49
128	CAL HIDRATADA	KG	200.00000	5.00	1000.00	50
129	HIPOCLORITO DE CALCIO	KG	200.00000	30.00	6000.00	50
131	SULFATO DE ALUMINIO	KG	200.00000	10.00	2000.00	50
130	PTAP COMPACTA ABIERTA METALICA 30 M3/HR	PZA	1.00000	878784.22	878784.22	50
132	PERFIL COSTANERAS	ML	36.00000	25.00	900.00	51
133	PINTURA ANTICORROSIVA	GL	4.00320	120.00	480.38	51
134	CALAMINA PREPINTADA ONDULADA Nº 28	M2	12.00000	42.00	504.00	51
135	ESTRUCTURA METÁLICA INCLUYE ACCESORIOS, SEGÚN PLANO	M2	12.00000	25.00	300.00	51
136	TUBERÍA FG 6"	ML	12.00000	580.00	6960.00	51
137	GANCHOS J PARA SUJECIÓN	PZA	30.00000	7.00	210.00	51
138	ACERO ESTRUCTURAL	KG	12.00000	8.50	102.00	52
139	PERFIL ANGULAR 2 X 1/8"	ML	3.00000	60.00	180.00	52
140	SOLDADURA	KG	1.20000	18.00	21.60	52
141	PINTURA ANTICORROSIVA	GL	0.25000	120.00	30.00	52
142	TABLERO DE DISTRIBUCIÓN	PZA	1.00000	5000.00	5000.00	53
143	CAMARA DE INSPECCION DE HºCº 80X80CM, SEGUN DISEÑO	PZA	1.00000	3500.00	3500.00	54
144	TIERRA CERNIDA	M3	1.20000	20.00	24.00	56
145	VÁLVULA DE PASO 6 PULG	PZA	1.00000	6801.43	6801.43	58
146	PINTADO ARTÍSTICO OBRA FPS	GLB	1.00000	18004.56	18004.56	59
72	CEMENTO	KG	5.00000	1.48	7.40	29
3	CEMENTO	KG	600.00000	1.48	888.00	2
88	CEMENTO	KG	10.00000	1.48	14.80	34
49	CEMENTO	KG	10.00000	1.48	14.80	12
122	CEMENTO	KG	100.00000	1.48	148.00	48
77	CEMENTO	KG	10.00000	1.48	14.80	31
108	CEMENTO	KG	350.00000	1.48	518.00	44
31	CEMENTO	KG	350.00000	1.48	518.00	7
105	CEMENTO	KG	20.00000	1.48	29.60	43
\.


--
-- Data for Name: users_modulo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_modulo (id, codigo, nombre, proyecto_id) FROM stdin;
1	001	PUENTE	1
2	001	ACTIVIDADES PRELIMINARES	2
3	002	TANQUE DE ALMACENAMIENTO SEMIENTERRADO	2
4	003	RED DE DISTRIBUCIÓN	2
5	004	CONEXIÓN DOMICILIARIA	2
6	005	SISTEMA DE BOMBEO	2
7	006	CASETA DE BOMBEO Y CLORACIÓN	2
8	007	MEDIDAS DE MITIGACIÓN AMBIENTAL Y DE ADAPTACIÓN AL CAMBIO CLIMÁTICO	2
9	008	PLANTA DE TRATAMIENTO DE AGUA POTABLE 30 M3/HR	2
\.


--
-- Data for Name: users_permiso; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_permiso (id, nombre, estado) FROM stdin;
1	GestionDeUsuarios	t
2	ListarRoles	t
3	ListarPermisos	t
4	ListarUsuarios	t
5	ListarUsuarioRol	t
6	ListarRolPermiso	t
7	Operaciones	t
8	GastosOperaciones	t
9	Reportes	t
\.


--
-- Data for Name: users_proyecto; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_proyecto (id_proyecto, "NombreProyecto", carga_social, iva_efectiva, herramientas, gastos_generales, iva_tasa_nominal, it, iue, ganancia, margen_utilidad, creado_por_id) FROM stdin;
1	ANÁLISIS DE PRECIOS UNITARIOS DE REFERENCIA PARA LA CONSTRUCCIÓN CAMINOS Y PUENTES EN ÁREA RURAL	71.00	14.94	5.00	13.00	13.00	3.00	25.00	70.00	10.28	2
2	AMPLIACIÓN DE RED Y CONSTRUCCIÓN PLANTA DE TRATAMIENTO DE AGUA POTABLE (SENA)	55.00	14.94	2.00	6.00	13.00	3.00	25.00	50.00	8.13	1
\.


--
-- Data for Name: users_registropendiente; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_registropendiente (id, token, datos, correo, creado_en, verificado) FROM stdin;
\.


--
-- Data for Name: users_rol; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_rol (id, nombre, estado) FROM stdin;
1	Administrador	t
2	Colaborador	t
3	Asistente	t
\.


--
-- Data for Name: users_rolpermiso; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_rolpermiso (id, permiso_id, rol_id) FROM stdin;
1	1	1
2	2	1
3	3	1
4	4	1
5	5	1
6	6	1
7	7	1
8	8	1
9	9	1
10	7	2
11	8	2
12	9	3
\.


--
-- Data for Name: users_temppasswordreset; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_temppasswordreset (id, token, temp_password, creado_en, usado, expirado, usuario_id) FROM stdin;
\.


--
-- Data for Name: users_usuario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_usuario (id, nombre, apellido, fecha_nacimiento, telefono, correo, password, ci, fecha_creacion, fecha_actualizacion, imagen_url, estado, intentos_fallidos, ultimo_intento, fecha_cambio_password, logins_exitosos, tipo_2fa, secret_2fa) FROM stdin;
3	Carla	Mamani	1995-07-10	70123456	carlamamani0000087985@gmail.com	pbkdf2_sha256$1200000$v2CJNqiYVxvuQhyxVwM2zR$WpVU+O8c83bjJsD4qr7cocZJaawKz1yrQdNQMPP1w1Y=	87654322	2026-02-22 06:16:10.135035+00	2026-02-22 06:16:10.135063+00		t	0	\N	\N	0	correo	\N
2	Andres Benito	Calle Yucra	1998-05-15	72937437	benitoandrescalle035@gmail.com	pbkdf2_sha256$1200000$LeXNogeu9XoKCD3NeMhjG5$tz2tKXg9Wwg0NPX0xtT7VlLiNUOw8fMIv1s2NRMEgV8=	87654321	2026-02-22 06:16:07.578371+00	2026-02-22 06:47:32.905099+00		t	0	2026-02-22 06:47:30.048294+00	\N	1	correo	V7UZMQDOYS4NK3IUYW5SL3F34DYKU36Q
1	Agapito	Yucra	1990-11-06	7121290	mallafinitasrl@gmail.com	pbkdf2_sha256$1200000$XdW4IpA72JJJw2tmGpOPKQ$bkWTdlD7QWzAJGn287LRkHAXW0B/7tIXR1VwKgHaWZE=	13247291	2026-02-22 06:16:05.012033+00	2026-02-24 03:02:06.218909+00		t	0	2026-02-24 03:02:06.218745+00	\N	7	correo	\N
\.


--
-- Data for Name: users_usuariorol; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users_usuariorol (id, rol_id, usuario_id) FROM stdin;
1	1	1
2	1	2
3	3	3
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 100, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 25, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 34, true);


--
-- Name: otp_static_staticdevice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.otp_static_staticdevice_id_seq', 1, false);


--
-- Name: otp_static_statictoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.otp_static_statictoken_id_seq', 1, false);


--
-- Name: otp_totp_totpdevice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.otp_totp_totpdevice_id_seq', 1, false);


--
-- Name: users_atacante_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_atacante_id_seq', 1, false);


--
-- Name: users_codigo2fa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_codigo2fa_id_seq', 7, true);


--
-- Name: users_equipoherramienta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_equipoherramienta_id_seq', 21, true);


--
-- Name: users_gastooperacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_gastooperacion_id_seq', 59, true);


--
-- Name: users_gastosgenerales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_gastosgenerales_id_seq', 59, true);


--
-- Name: users_manodeobra_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_manodeobra_id_seq', 123, true);


--
-- Name: users_materiales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_materiales_id_seq', 146, true);


--
-- Name: users_modulo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_modulo_id_seq', 9, true);


--
-- Name: users_permiso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_permiso_id_seq', 9, true);


--
-- Name: users_proyecto_id_proyecto_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_proyecto_id_proyecto_seq', 2, true);


--
-- Name: users_registropendiente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_registropendiente_id_seq', 1, false);


--
-- Name: users_rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_rol_id_seq', 3, true);


--
-- Name: users_rolpermiso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_rolpermiso_id_seq', 12, true);


--
-- Name: users_temppasswordreset_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_temppasswordreset_id_seq', 1, false);


--
-- Name: users_usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_usuario_id_seq', 3, true);


--
-- Name: users_usuariorol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_usuariorol_id_seq', 3, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: otp_static_staticdevice otp_static_staticdevice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_static_staticdevice
    ADD CONSTRAINT otp_static_staticdevice_pkey PRIMARY KEY (id);


--
-- Name: otp_static_statictoken otp_static_statictoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_static_statictoken
    ADD CONSTRAINT otp_static_statictoken_pkey PRIMARY KEY (id);


--
-- Name: otp_totp_totpdevice otp_totp_totpdevice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_totp_totpdevice
    ADD CONSTRAINT otp_totp_totpdevice_pkey PRIMARY KEY (id);


--
-- Name: users_modulo uq_modulo_codigo_por_proyecto; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_modulo
    ADD CONSTRAINT uq_modulo_codigo_por_proyecto UNIQUE (proyecto_id, codigo);


--
-- Name: users_proyecto uq_proyecto_por_usuario; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_proyecto
    ADD CONSTRAINT uq_proyecto_por_usuario UNIQUE (creado_por_id, "NombreProyecto");


--
-- Name: users_atacante users_atacante_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_atacante
    ADD CONSTRAINT users_atacante_pkey PRIMARY KEY (id);


--
-- Name: users_codigo2fa users_codigo2fa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_codigo2fa
    ADD CONSTRAINT users_codigo2fa_pkey PRIMARY KEY (id);


--
-- Name: users_equipoherramienta users_equipoherramienta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_equipoherramienta
    ADD CONSTRAINT users_equipoherramienta_pkey PRIMARY KEY (id);


--
-- Name: users_gastooperacion users_gastooperacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_gastooperacion
    ADD CONSTRAINT users_gastooperacion_pkey PRIMARY KEY (id);


--
-- Name: users_gastosgenerales users_gastosgenerales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_gastosgenerales
    ADD CONSTRAINT users_gastosgenerales_pkey PRIMARY KEY (id);


--
-- Name: users_manodeobra users_manodeobra_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_manodeobra
    ADD CONSTRAINT users_manodeobra_pkey PRIMARY KEY (id);


--
-- Name: users_materiales users_materiales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_materiales
    ADD CONSTRAINT users_materiales_pkey PRIMARY KEY (id);


--
-- Name: users_modulo users_modulo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_modulo
    ADD CONSTRAINT users_modulo_pkey PRIMARY KEY (id);


--
-- Name: users_permiso users_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_permiso
    ADD CONSTRAINT users_permiso_pkey PRIMARY KEY (id);


--
-- Name: users_proyecto users_proyecto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_proyecto
    ADD CONSTRAINT users_proyecto_pkey PRIMARY KEY (id_proyecto);


--
-- Name: users_registropendiente users_registropendiente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_registropendiente
    ADD CONSTRAINT users_registropendiente_pkey PRIMARY KEY (id);


--
-- Name: users_registropendiente users_registropendiente_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_registropendiente
    ADD CONSTRAINT users_registropendiente_token_key UNIQUE (token);


--
-- Name: users_rol users_rol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_rol
    ADD CONSTRAINT users_rol_pkey PRIMARY KEY (id);


--
-- Name: users_rolpermiso users_rolpermiso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_rolpermiso
    ADD CONSTRAINT users_rolpermiso_pkey PRIMARY KEY (id);


--
-- Name: users_rolpermiso users_rolpermiso_rol_id_permiso_id_fb816590_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_rolpermiso
    ADD CONSTRAINT users_rolpermiso_rol_id_permiso_id_fb816590_uniq UNIQUE (rol_id, permiso_id);


--
-- Name: users_temppasswordreset users_temppasswordreset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_temppasswordreset
    ADD CONSTRAINT users_temppasswordreset_pkey PRIMARY KEY (id);


--
-- Name: users_temppasswordreset users_temppasswordreset_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_temppasswordreset
    ADD CONSTRAINT users_temppasswordreset_token_key UNIQUE (token);


--
-- Name: users_usuario users_usuario_ci_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_usuario
    ADD CONSTRAINT users_usuario_ci_key UNIQUE (ci);


--
-- Name: users_usuario users_usuario_correo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_usuario
    ADD CONSTRAINT users_usuario_correo_key UNIQUE (correo);


--
-- Name: users_usuario users_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_usuario
    ADD CONSTRAINT users_usuario_pkey PRIMARY KEY (id);


--
-- Name: users_usuariorol users_usuariorol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_usuariorol
    ADD CONSTRAINT users_usuariorol_pkey PRIMARY KEY (id);


--
-- Name: users_usuariorol users_usuariorol_usuario_id_rol_id_49e0e5ad_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_usuariorol
    ADD CONSTRAINT users_usuariorol_usuario_id_rol_id_49e0e5ad_uniq UNIQUE (usuario_id, rol_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: otp_static_staticdevice_user_id_7f9cff2b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX otp_static_staticdevice_user_id_7f9cff2b ON public.otp_static_staticdevice USING btree (user_id);


--
-- Name: otp_static_statictoken_device_id_74b7c7d1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX otp_static_statictoken_device_id_74b7c7d1 ON public.otp_static_statictoken USING btree (device_id);


--
-- Name: otp_static_statictoken_token_d0a51866; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX otp_static_statictoken_token_d0a51866 ON public.otp_static_statictoken USING btree (token);


--
-- Name: otp_static_statictoken_token_d0a51866_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX otp_static_statictoken_token_d0a51866_like ON public.otp_static_statictoken USING btree (token varchar_pattern_ops);


--
-- Name: otp_totp_totpdevice_user_id_0fb18292; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX otp_totp_totpdevice_user_id_0fb18292 ON public.otp_totp_totpdevice USING btree (user_id);


--
-- Name: users_atacante_fingerprint_b46f2a95; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_atacante_fingerprint_b46f2a95 ON public.users_atacante USING btree (fingerprint);


--
-- Name: users_atacante_fingerprint_b46f2a95_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_atacante_fingerprint_b46f2a95_like ON public.users_atacante USING btree (fingerprint varchar_pattern_ops);


--
-- Name: users_codigo2fa_usuario_id_80b99c49; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_codigo2fa_usuario_id_80b99c49 ON public.users_codigo2fa USING btree (usuario_id);


--
-- Name: users_equipoherramienta_gasto_operacion_id_b883792b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_equipoherramienta_gasto_operacion_id_b883792b ON public.users_equipoherramienta USING btree (gasto_operacion_id);


--
-- Name: users_gastooperacion_modulo_id_77e739e0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_gastooperacion_modulo_id_77e739e0 ON public.users_gastooperacion USING btree (modulo_id);


--
-- Name: users_gastosgenerales_gasto_operacion_id_3d499afa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_gastosgenerales_gasto_operacion_id_3d499afa ON public.users_gastosgenerales USING btree (gasto_operacion_id);


--
-- Name: users_manodeobra_gasto_operacion_id_01451a22; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_manodeobra_gasto_operacion_id_01451a22 ON public.users_manodeobra USING btree (gasto_operacion_id);


--
-- Name: users_materiales_gasto_operacion_id_7bbdc4f1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_materiales_gasto_operacion_id_7bbdc4f1 ON public.users_materiales USING btree (gasto_operacion_id);


--
-- Name: users_modulo_proyecto_id_058371fd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_modulo_proyecto_id_058371fd ON public.users_modulo USING btree (proyecto_id);


--
-- Name: users_proyecto_creado_por_id_cf821194; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_proyecto_creado_por_id_cf821194 ON public.users_proyecto USING btree (creado_por_id);


--
-- Name: users_rolpermiso_permiso_id_75522150; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_rolpermiso_permiso_id_75522150 ON public.users_rolpermiso USING btree (permiso_id);


--
-- Name: users_rolpermiso_rol_id_0abe7f76; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_rolpermiso_rol_id_0abe7f76 ON public.users_rolpermiso USING btree (rol_id);


--
-- Name: users_temppasswordreset_usuario_id_30110be2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_temppasswordreset_usuario_id_30110be2 ON public.users_temppasswordreset USING btree (usuario_id);


--
-- Name: users_usuario_ci_640c1cbd_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_usuario_ci_640c1cbd_like ON public.users_usuario USING btree (ci varchar_pattern_ops);


--
-- Name: users_usuario_correo_6774d8f3_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_usuario_correo_6774d8f3_like ON public.users_usuario USING btree (correo varchar_pattern_ops);


--
-- Name: users_usuariorol_rol_id_c7570d7e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_usuariorol_rol_id_c7570d7e ON public.users_usuariorol USING btree (rol_id);


--
-- Name: users_usuariorol_usuario_id_bc8607dd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_usuariorol_usuario_id_bc8607dd ON public.users_usuariorol USING btree (usuario_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_static_staticdevice otp_static_staticdevice_user_id_7f9cff2b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_static_staticdevice
    ADD CONSTRAINT otp_static_staticdevice_user_id_7f9cff2b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_static_statictoken otp_static_statictok_device_id_74b7c7d1_fk_otp_stati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_static_statictoken
    ADD CONSTRAINT otp_static_statictok_device_id_74b7c7d1_fk_otp_stati FOREIGN KEY (device_id) REFERENCES public.otp_static_staticdevice(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: otp_totp_totpdevice otp_totp_totpdevice_user_id_0fb18292_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_totp_totpdevice
    ADD CONSTRAINT otp_totp_totpdevice_user_id_0fb18292_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_codigo2fa users_codigo2fa_usuario_id_80b99c49_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_codigo2fa
    ADD CONSTRAINT users_codigo2fa_usuario_id_80b99c49_fk_users_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_equipoherramienta users_equipoherramie_gasto_operacion_id_b883792b_fk_users_gas; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_equipoherramienta
    ADD CONSTRAINT users_equipoherramie_gasto_operacion_id_b883792b_fk_users_gas FOREIGN KEY (gasto_operacion_id) REFERENCES public.users_gastooperacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_gastooperacion users_gastooperacion_modulo_id_77e739e0_fk_users_modulo_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_gastooperacion
    ADD CONSTRAINT users_gastooperacion_modulo_id_77e739e0_fk_users_modulo_id FOREIGN KEY (modulo_id) REFERENCES public.users_modulo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_gastosgenerales users_gastosgenerale_gasto_operacion_id_3d499afa_fk_users_gas; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_gastosgenerales
    ADD CONSTRAINT users_gastosgenerale_gasto_operacion_id_3d499afa_fk_users_gas FOREIGN KEY (gasto_operacion_id) REFERENCES public.users_gastooperacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_manodeobra users_manodeobra_gasto_operacion_id_01451a22_fk_users_gas; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_manodeobra
    ADD CONSTRAINT users_manodeobra_gasto_operacion_id_01451a22_fk_users_gas FOREIGN KEY (gasto_operacion_id) REFERENCES public.users_gastooperacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_materiales users_materiales_gasto_operacion_id_7bbdc4f1_fk_users_gas; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_materiales
    ADD CONSTRAINT users_materiales_gasto_operacion_id_7bbdc4f1_fk_users_gas FOREIGN KEY (gasto_operacion_id) REFERENCES public.users_gastooperacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_modulo users_modulo_proyecto_id_058371fd_fk_users_proyecto_id_proyecto; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_modulo
    ADD CONSTRAINT users_modulo_proyecto_id_058371fd_fk_users_proyecto_id_proyecto FOREIGN KEY (proyecto_id) REFERENCES public.users_proyecto(id_proyecto) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_proyecto users_proyecto_creado_por_id_cf821194_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_proyecto
    ADD CONSTRAINT users_proyecto_creado_por_id_cf821194_fk_users_usuario_id FOREIGN KEY (creado_por_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_rolpermiso users_rolpermiso_permiso_id_75522150_fk_users_permiso_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_rolpermiso
    ADD CONSTRAINT users_rolpermiso_permiso_id_75522150_fk_users_permiso_id FOREIGN KEY (permiso_id) REFERENCES public.users_permiso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_rolpermiso users_rolpermiso_rol_id_0abe7f76_fk_users_rol_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_rolpermiso
    ADD CONSTRAINT users_rolpermiso_rol_id_0abe7f76_fk_users_rol_id FOREIGN KEY (rol_id) REFERENCES public.users_rol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_temppasswordreset users_temppasswordreset_usuario_id_30110be2_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_temppasswordreset
    ADD CONSTRAINT users_temppasswordreset_usuario_id_30110be2_fk_users_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_usuariorol users_usuariorol_rol_id_c7570d7e_fk_users_rol_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_usuariorol
    ADD CONSTRAINT users_usuariorol_rol_id_c7570d7e_fk_users_rol_id FOREIGN KEY (rol_id) REFERENCES public.users_rol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_usuariorol users_usuariorol_usuario_id_bc8607dd_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_usuariorol
    ADD CONSTRAINT users_usuariorol_usuario_id_bc8607dd_fk_users_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict PRWiKZ3Rq1i1MioIowhOiRP4XITCn2xiPCMdDQF8rA2kfdjpldaE2j2nH183Pb9

